Bezpieczeństwo systemów LAB/Models/AlphabetEnum.cs
namespace Bezpieczeństwo_systemów_LAB.Models;

public enum AlphabetEnum
{
    a, ą, b, c, ć, d, e, ę, f, g, h, i, j, k, l, ł, m, n, ń, o, ó, p, q, r, s, ś, t, u, v, w, x, y, z, ź, ż
}

Bezpieczeństwo systemów LAB/Models/ErrorViewModel.cs
namespace Bezpieczeństwo_systemów_LAB.Models;

public class ErrorViewModel
{
    public string? RequestId { get; set; }

    public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
}

Bezpieczeństwo systemów LAB/Models/MethodsEnum.cs
namespace Bezpieczeństwo_systemów_LAB.Models;

public enum MethodsEnum
{
    Encrypt,Decrypt
}

Bezpieczeństwo systemów LAB/Models/SzyfrCezara.cs
namespace Bezpieczeństwo_systemów_LAB.Models;

public class SzyfrCezara
{
    public string? text { get; set; }
    public int? step { get; set; }
    public string? method { get; set; }

    public bool IsValid()
    {
        return text != null && step != null && method != null;
    }
    

    public string Encrypt()
    {
        step = step % 35;
        if (step<0)
        {
            step += 35;
        }
        string result = null;

        string Clearedtext = string.Join("", text.Where(c => char.IsLetterOrDigit(c))).ToLower();

        for (int i = 0; i < Clearedtext.Length; i++)
        {
            char letter = Clearedtext[i];
            int index = Array.IndexOf(Enum.GetNames(typeof(AlphabetEnum)), letter.ToString());
            int EncryptedIndex =index +step.Value;
            if (EncryptedIndex > 34)
            {
                EncryptedIndex -=35;
            }
            
            AlphabetEnum? EncryptedLetter =(AlphabetEnum)EncryptedIndex;
            result+=EncryptedLetter.ToString();
        }
        return result;
    }
    
    public string Decrypt()
    {
        step = step % 35;
        if (step<0)
        {
            step += 35;
        }
        string result = null;

        string Clearedtext = string.Join("", text.Split(' ')).ToLower();

        for (int i = 0; i < Clearedtext.Length; i++)
        {
            char letter = Clearedtext[i];
            int index = Array.IndexOf(Enum.GetNames(typeof(AlphabetEnum)), letter.ToString());
            int EncryptedIndex =index -step.Value;
            if (EncryptedIndex <0)
            {
                EncryptedIndex +=35;
            }
            
            AlphabetEnum? EncryptedLetter =(AlphabetEnum)EncryptedIndex;
            result+=EncryptedLetter.ToString();
        }
        return result;
    }
}

Bezpieczeństwo systemów LAB/Models/SzyfrCezara/SzyfrCezaraEncrypt.cs
namespace Bezpieczeństwo_systemów_LAB.Models;

public class SzyfrCezaraEncrypt
{
    public string? text { get; set; }
    public int? step { get; set; }

    public bool IsValid()
    {
        return text != null && step != null;
    }

    public string Encrypt()
    {
        step = step % 35;
        if (step<0)
        {
            step += 35;
        }
        string result = null;

        string Clearedtext = string.Join("", text.Split(' ')).ToLower();

        for (int i = 0; i < Clearedtext.Length; i++)
        {
            char letter = Clearedtext[i];
            int index = Array.IndexOf(Enum.GetNames(typeof(AlphabetEnum)), letter.ToString());
            int EncryptedIndex =index +step.Value;
            if (EncryptedIndex > 34)
            {
                EncryptedIndex -=35;
            }
            
            AlphabetEnum? EncryptedLetter =(AlphabetEnum)EncryptedIndex;
            result+=EncryptedLetter.ToString();
        }
        return result;
    }
}

Bezpieczeństwo systemów LAB/Controllers/HomeController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using Bezpieczeństwo_systemów_LAB.Models;

namespace Bezpieczeństwo_systemów_LAB.Controllers;

public class HomeController : Controller
{
    private readonly ILogger<HomeController> _logger;

    public HomeController(ILogger<HomeController> logger)
    {
        _logger = logger;
    }

    public IActionResult Index()
    {
        return View();
    }

    public IActionResult Privacy()
    {
        return View();
    }

    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    public IActionResult Error()
    {
        return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
    }
}

Bezpieczeństwo systemów LAB/Controllers/SzyfrCezaraController.cs
using Bezpieczeństwo_systemów_LAB.Models;
using Microsoft.AspNetCore.Mvc;

namespace Bezpieczeństwo_systemów_LAB.Controllers;

public class SzyfrCezaraController : Controller
{
    public IActionResult Form()
    {
        return View();
    }

    public IActionResult Result(SzyfrCezara model)
    {
        if (!model.IsValid())
        {
            return View("SzyfrCezaraError");
        }
        return View(model);
    }
}

Bezpieczeństwo systemów LAB/Controllers/SzyfrPolibiuszaController.cs
using Microsoft.AspNetCore.Mvc;

namespace Bezpieczeństwo_systemów_LAB.Controllers;

public class SzyfrPolibiuszaController : Controller
{
    
    public IActionResult Form()
    {
        return View();
    }
}

Bezpieczeństwo systemów LAB/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://learn.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

Bezpieczeństwo systemów LAB/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <title>@ViewData["Title"] - Bezpieczeństwo_systemów_LAB</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css"/>
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true"/>
    <link rel="stylesheet" href="~/Bezpieczeństwo_systemów_LAB.styles.css" asp-append-version="true"/>
</head>
<body>
<header>
    <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
        <div class="container-fluid">
            <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Bezpieczeństwo_systemów_LAB</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                    aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                <ul class="navbar-nav flex-grow-1">
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="SzyfrCezara" asp-action="Form">Szyfr Cezara</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="SzyfrPolibiusza" asp-action="Form">Szyfr Polibiusza</a>
                    </li>
                </ul>
            </div>
        </div>
    </nav>
</header>
<div class="container">
    <main role="main" class="pb-3">
        @RenderBody()
    </main>
</div>

<footer class="border-top footer text-muted">
    <div class="container">
        &copy; 2024 - Bezpieczeństwo_systemów_LAB - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
    </div>
</footer>
<script src="~/lib/jquery/dist/jquery.min.js"></script>
<script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
<script src="~/js/site.js" asp-append-version="true"></script>
@await RenderSectionAsync("Scripts", required: false)
</body>
</html>

Bezpieczeństwo systemów LAB/Views/SzyfrCezara/Form.cshtml
<div class="container">
    <h1 class="text-center">Szyfr Cezara</h1>
    <div class="row justify-content-center">
        <div class="col-md-10">
            <form action="Result" method="GET">
                <div class="form-group">
                    <label for="tekst">Wpisz tekst:</label>
                    <textarea type="" class="form-control w-100" id="tekst" rows="10" name="text"></textarea>
                </div>
                <div class="form-group">
                    <label for="klucz">Klucz:</label>
                    <input type="number" class="form-control mb-0" id="klucz" value="3" name="step">
                    <small class="form-text mt-0 text-muted">0 - brak przesunięcia</small>
                </div>
                <button type="submit" value="Encrypt" name="method" class="btn btn-primary">Zaszyfruj</button>
                <button type="submit" value="Decrypt" name="method" class="btn btn-secondary">Odszyfruj</button>
            </form>

        </div>
    </div>
</div>

Bezpieczeństwo systemów LAB/Views/SzyfrCezara/Result.cshtml
@model SzyfrCezara

@{
ViewBag.Title = "Szyfr Cezara";
Layout = "_Layout";
}

<div class="container mt-5">
    <h1 class="text-center">Szyfr Cezara</h1>

    <div class="mb-3">
        <div>Tekst:</div>
        <div class="alert alert-secondary text-break" >@Model.text</div>
    </div>

    <div class="mb-3">
        <div>Klucz (przesunięcie):</div>
        <div class="alert alert-secondary text-break">@Model.step</div>
    </div>

    <h2>Wynik:</h2>
    <div id="result" class="alert alert-secondary text-break" role="alert">
        @if (Model.method == MethodsEnum.Encrypt.ToString())
        {
        @Model.Encrypt()
        }
        else
        {
        @Model.Decrypt()
        }
    </div>
    <button id="copyButton" class="btn btn-primary mt-3">Kopiuj wynik</button>
</div>
<script>
    document.getElementById('copyButton').addEventListener('click', function() {
        var resultText = document.getElementById('result').innerText;
        var textarea = document.createElement('textarea');
        textarea.value = resultText;
        document.body.appendChild(textarea);
        textarea.select();
        document.execCommand('copy');

        document.body.removeChild(textarea);
    });
</script>

Bezpieczeństwo systemów LAB/Views/SzyfrCezara/SzyfrCezaraError.cshtml
@model dynamic

@{
    ViewBag.Title = "title";
    Layout = "_Layout";
}

<div class="container mt-5">
    <div class="alert alert-danger" role="alert">
        <h4 class="alert-heading">Coś poszło nie tak!</h4>
        <p>Niepoprawnu format dannych!</p>
    </div>
</div>

Bezpieczeństwo systemów LAB/Views/SzyfrPolibiusza/Form.cshtml
<div class="container mt-5">
    <h1 class="text-center">Szyfr Polibiusza</h1>
    <form>
        <div class="form-group">
            <label for="keyInput">Wprowadź klucz (Litery nie mogą się powtarzać):</label>
            <table class="table table-bordered">
                <tbody>
                <tr>
                    <td><input type="text" class="form-control" maxlength="1"></td>
                    <td><input type="text" class="form-control" maxlength="1"></td>
                    <td><input type="text" class="form-control" maxlength="1"></td>
                    <td><input type="text" class="form-control" maxlength="1"></td>
                    <td><input type="text" class="form-control" maxlength="1"></td>
                    <td><input type="text" class="form-control" maxlength="1"></td>
                    <td><input type="text" class="form-control" maxlength="1"></td>
                </tr>
                <tr>
                    <td><input type="text" class="form-control" maxlength="1"></td>
                    <td><input type="text" class="form-control" maxlength="1"></td>
                    <td><input type="text" class="form-control" maxlength="1"></td>
                    <td><input type="text" class="form-control" maxlength="1"></td>
                    <td><input type="text" class="form-control" maxlength="1"></td>
                    <td><input type="text" class="form-control" maxlength="1"></td>
                    <td><input type="text" class="form-control" maxlength="1"></td>
                </tr>
                <tr>
                    <td><input type="text" class="form-control" maxlength="1"></td>
                    <td><input type="text" class="form-control" maxlength="1"></td>
                    <td><input type="text" class="form-control" maxlength="1"></td>
                    <td><input type="text" class="form-control" maxlength="1"></td>
                    <td><input type="text" class="form-control" maxlength="1"></td>
                    <td><input type="text" class="form-control" maxlength="1"></td>
                    <td><input type="text" class="form-control" maxlength="1"></td>
                </tr>
                <tr>
                    <td><input type="text" class="form-control" maxlength="1"></td>
                    <td><input type="text" class="form-control" maxlength="1"></td>
                    <td><input type="text" class="form-control" maxlength="1"></td>
                    <td><input type="text" class="form-control" maxlength="1"></td>
                    <td><input type="text" class="form-control" maxlength="1"></td>
                    <td><input type="text" class="form-control" maxlength="1"></td>
                    <td><input type="text" class="form-control" maxlength="1"></td>
                </tr>
                <tr>
                    <td><input type="text" class="form-control" maxlength="1"></td>
                    <td><input type="text" class="form-control" maxlength="1"></td>
                    <td><input type="text" class="form-control" maxlength="1"></td>
                    <td><input type="text" class="form-control" maxlength="1"></td>
                    <td><input type="text" class="form-control" maxlength="1"></td>
                    <td><input type="text" class="form-control" maxlength="1"></td>
                    <td><input type="text" class="form-control" maxlength="1"></td>
                </tr>
                
                </tbody>
            </table>
        </div>
        <div class="form-group mb-3">
            <label for="inputText">Wprowadź tekst do zaszyfrowania:</label>
            <textarea type="" class="form-control w-100" id="tekst" rows="10" name="text"></textarea>
        </div>
        <button type="submit" value="Encrypt" name="method" class="btn btn-primary">Zaszyfruj</button>
        <button type="submit" value="Decrypt" name="method" class="btn btn-secondary">Odszyfruj</button>
    </form>
</div>